-- =====================================================================
--  MONITOR B3 (versão de aula) — schema completo do Supabase
--  Execute no SQL Editor, uma única vez, de cima para baixo.
--
--  8 tabelas:
--   MERCADO (compartilhadas, só leitura para o app):
--     setores ──< ativos ──< precos_diarios
--                       └──< previsoes >── modelos
--   USUÁRIO (privadas, cada um vê só o que é seu):
--     auth.users ── profiles ──< carteiras ──< carteira_itens >── ativos
--   STORAGE: bucket 'avatares' com a foto de cada usuário (link em profiles.avatar_url)
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. TABELAS DE MERCADO
-- ---------------------------------------------------------------------

-- Setores da economia (1 setor tem N ações)
create table public.setores (
  id   bigint generated by default as identity primary key,
  nome text not null unique
);

-- Ações acompanhadas pelo app (N ações pertencem a 1 setor)
create table public.ativos (
  ticker   text primary key,                          -- ex.: 'PETR4' (sem o .SA)
  nome     text not null,
  setor_id bigint not null references public.setores(id),
  ativo    boolean not null default true              -- false = o pipeline ignora
);

-- Cotações diárias (1 ação tem N cotações; chave = ação + data)
create table public.precos_diarios (
  ticker     text not null references public.ativos(ticker) on delete cascade,
  data       date not null,
  abertura   numeric(12,4),
  maxima     numeric(12,4),
  minima     numeric(12,4),
  fechamento numeric(12,4) not null,
  volume     bigint,
  primary key (ticker, data)
);

-- Cada treino diário do modelo gera uma versão
create table public.modelos (
  versao       text primary key,                      -- ex.: '2026-09-30T22-05'
  treinado_em  timestamptz not null default now(),
  n_amostras   integer,
  ic_validacao double precision                       -- qualidade medida na validação
);

-- Previsão de retorno para os próximos 5 pregões, uma por ação e por dia
create table public.previsoes (
  data_referencia   date not null,
  ticker            text not null references public.ativos(ticker) on delete cascade,
  modelo_versao     text not null references public.modelos(versao) on delete cascade,
  retorno_previsto  double precision not null,
  posicao           integer not null,                 -- 1 = maior retorno previsto
  retorno_realizado double precision,                 -- preenchido 5 pregões depois
  primary key (data_referencia, ticker)
);


-- ---------------------------------------------------------------------
-- 2. TABELAS DO USUÁRIO
-- ---------------------------------------------------------------------

-- Perfil: 1 para 1 com o usuário do Supabase Auth
create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  nome       text,
  avatar_url text,                                    -- link da foto no Storage (bucket 'avatares')
  created_at timestamptz not null default now()
);

-- Carteiras montadas pelo usuário (1 usuário tem N carteiras)
create table public.carteiras (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  nome            text not null,
  data_referencia date not null,
  created_at      timestamptz not null default now()
);

-- Ações de cada carteira: liga carteiras e ativos (relação N para N)
create table public.carteira_itens (
  carteira_id bigint not null references public.carteiras(id) on delete cascade,
  ticker      text   not null references public.ativos(ticker),
  peso        numeric(5,4) not null check (peso > 0 and peso <= 1),
  primary key (carteira_id, ticker)
);


-- ---------------------------------------------------------------------
-- 3. DADOS INICIAIS: setores e ações
-- ---------------------------------------------------------------------
insert into public.setores (nome) values
  ('Petróleo e gás'), ('Mineração'), ('Siderurgia'), ('Papel e celulose'),
  ('Bancos'), ('Serviços financeiros'), ('Energia elétrica'), ('Saneamento'),
  ('Telecom'), ('Tecnologia'), ('Bens de capital'), ('Locação'),
  ('Bebidas'), ('Saúde'), ('Varejo'), ('Construção')
on conflict (nome) do nothing;

insert into public.ativos (ticker, nome, setor_id)
select a.ticker, a.nome, s.id
from (values
  ('PETR4',  'Petrobras PN',      'Petróleo e gás'),
  ('PRIO3',  'PRIO',              'Petróleo e gás'),
  ('VALE3',  'Vale',              'Mineração'),
  ('GGBR4',  'Gerdau PN',         'Siderurgia'),
  ('SUZB3',  'Suzano',            'Papel e celulose'),
  ('KLBN11', 'Klabin Unit',       'Papel e celulose'),
  ('ITUB4',  'Itaú Unibanco PN',  'Bancos'),
  ('BBDC4',  'Bradesco PN',       'Bancos'),
  ('BBAS3',  'Banco do Brasil',   'Bancos'),
  ('BPAC11', 'BTG Pactual Unit',  'Bancos'),
  ('ITSA4',  'Itaúsa PN',         'Bancos'),
  ('B3SA3',  'B3',                'Serviços financeiros'),
  ('EQTL3',  'Equatorial',        'Energia elétrica'),
  ('CMIG4',  'Cemig PN',          'Energia elétrica'),
  ('SBSP3',  'Sabesp',            'Saneamento'),
  ('VIVT3',  'Telefônica Brasil', 'Telecom'),
  ('TOTS3',  'Totvs',             'Tecnologia'),
  ('WEGE3',  'WEG',               'Bens de capital'),
  ('RENT3',  'Localiza',          'Locação'),
  ('ABEV3',  'Ambev',             'Bebidas'),
  ('RADL3',  'Raia Drogasil',     'Saúde'),
  ('LREN3',  'Lojas Renner',      'Varejo'),
  ('MGLU3',  'Magazine Luiza',    'Varejo'),
  ('CYRE3',  'Cyrela',            'Construção')
) as a(ticker, nome, setor)
join public.setores s on s.nome = a.setor
on conflict (ticker) do nothing;


-- ---------------------------------------------------------------------
-- 4. TRIGGER: todo usuário novo ganha uma linha em profiles
-- ---------------------------------------------------------------------
create or replace function public.criar_perfil()
returns trigger language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, nome)
  values (new.id, new.raw_user_meta_data ->> 'nome');
  return new;
end;
$$;

create trigger ao_criar_usuario
  after insert on auth.users
  for each row execute function public.criar_perfil();


-- ---------------------------------------------------------------------
-- 5. VIEWS para o frontend
--    security_invoker = true: a view respeita a RLS de quem consulta
-- ---------------------------------------------------------------------

-- Ranking do último pregão, com nome, setor e último preço
create view public.v_ranking_atual with (security_invoker = true) as
select p.posicao, p.ticker, a.nome, s.nome as setor,
       p.retorno_previsto, pr.fechamento as ultimo_preco,
       p.data_referencia, p.modelo_versao
from public.previsoes p
join public.ativos  a on a.ticker = p.ticker
join public.setores s on s.id = a.setor_id
left join public.precos_diarios pr on pr.ticker = p.ticker and pr.data = p.data_referencia
where p.data_referencia = (select max(data_referencia) from public.previsoes);

-- Resultado de cada carteira do usuário: previsto × realizado
create view public.v_desempenho_carteiras with (security_invoker = true) as
select c.id as carteira_id, c.user_id, c.nome, c.data_referencia,
       count(*)                              as n_acoes,
       sum(i.peso * p.retorno_previsto)      as retorno_previsto,
       sum(i.peso * p.retorno_realizado)     as retorno_realizado,
       count(p.retorno_realizado) = count(*) as concluida
from public.carteiras c
join public.carteira_itens i on i.carteira_id = c.id
left join public.previsoes p on p.ticker = i.ticker and p.data_referencia = c.data_referencia
group by c.id;


-- ---------------------------------------------------------------------
-- 6. FUNÇÃO chamada pelo frontend: monta uma carteira com as N melhores
--    previsões do último pregão, com pesos iguais. Retorna o id criado.
-- ---------------------------------------------------------------------
create or replace function public.montar_carteira(p_n integer default 5, p_nome text default null)
returns bigint
language plpgsql security invoker set search_path = public
as $$
declare
  v_data date;
  v_id   bigint;
begin
  if auth.uid() is null then
    raise exception 'É preciso estar logado';
  end if;
  if p_n not between 1 and 20 then
    raise exception 'Escolha entre 1 e 20 ações';
  end if;

  select max(data_referencia) into v_data from previsoes;
  if v_data is null then
    raise exception 'Ainda não há previsões';
  end if;

  insert into carteiras (nome, data_referencia)
  values (coalesce(p_nome, 'Carteira de ' || to_char(v_data, 'DD/MM/YYYY')), v_data)
  returning id into v_id;

  insert into carteira_itens (carteira_id, ticker, peso)
  select v_id, t.ticker, round(1.0 / count(*) over (), 4)
  from (select ticker from previsoes
        where data_referencia = v_data
        order by posicao
        limit p_n) t;

  return v_id;
end;
$$;


-- ---------------------------------------------------------------------
-- 7. SEGURANÇA — Row Level Security
-- ---------------------------------------------------------------------
alter table public.setores        enable row level security;
alter table public.ativos         enable row level security;
alter table public.precos_diarios enable row level security;
alter table public.modelos        enable row level security;
alter table public.previsoes      enable row level security;
alter table public.profiles       enable row level security;
alter table public.carteiras      enable row level security;
alter table public.carteira_itens enable row level security;

-- Mercado: qualquer usuário logado lê; ninguém escreve pelo app
-- (o pipeline Python escreve com a chave secreta, que ignora a RLS)
create policy "leitura para logados" on public.setores        for select to authenticated using (true);
create policy "leitura para logados" on public.ativos         for select to authenticated using (true);
create policy "leitura para logados" on public.precos_diarios for select to authenticated using (true);
create policy "leitura para logados" on public.modelos        for select to authenticated using (true);
create policy "leitura para logados" on public.previsoes      for select to authenticated using (true);

-- Usuário: cada um só vê e altera o que é seu
create policy "ver o próprio perfil" on public.profiles for select to authenticated
  using (id = auth.uid());
create policy "editar o próprio perfil" on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

create policy "dono da carteira" on public.carteiras for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "dono da carteira" on public.carteira_itens for all to authenticated
  using (exists (select 1 from public.carteiras c
                 where c.id = carteira_id and c.user_id = auth.uid()))
  with check (exists (select 1 from public.carteiras c
                      where c.id = carteira_id and c.user_id = auth.uid()));


-- ---------------------------------------------------------------------
-- 8. STORAGE — foto de cada usuário
--    Arquivo em avatares/<id do usuário>/avatar; cada um só mexe na própria pasta.
--    Bucket público: quem tiver o link vê a foto (adequado para avatar).
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatares', 'avatares', true, 2097152,                 -- até 2 MB
        array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do nothing;

create policy "avatares: logados veem" on storage.objects for select to authenticated
  using (bucket_id = 'avatares');

create policy "avatares: enviar na própria pasta" on storage.objects for insert to authenticated
  with check (bucket_id = 'avatares' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "avatares: trocar na própria pasta" on storage.objects for update to authenticated
  using (bucket_id = 'avatares' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'avatares' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "avatares: apagar da própria pasta" on storage.objects for delete to authenticated
  using (bucket_id = 'avatares' and (storage.foldername(name))[1] = auth.uid()::text);


-- Visitantes não logados não acessam nada
revoke all on all tables in schema public from anon;
revoke execute on function public.montar_carteira(integer, text) from anon, public;
grant  execute on function public.montar_carteira(integer, text) to authenticated;
